version: "3.8"

services:
  lidarr-ytdlp:
    image: lpuffyy/lidarr-ytdlp:latest
    container_name: lidarr-ytdlp
    restart: unless-stopped
    ports:
      - "5004:5004"          # Dashboard port
    environment:
      - TZ=Etc/UTC
      - LIDARR_URL=http://localhost:8686/api/v1
      - LIDARR_API_KEY=changeme
      - MUSIC_DIR=/music
      - CHECK_INTERVAL=3600  # how often to check for wanted tracks (seconds)
    volumes:
      - /path/to/music:/music
      - /path/to/config:/config   # optional, if you want persistent logs/config
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5004"]
